version: '3.8'

services:
  node:
    build: .
    container_name: nmm_django
    # command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    networks:
      - jungle_network

networks:
  jungle_network:
    driver: bridge