# This is a basic workflow to help you get started with Actions
name: CI/CD Workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main", "backend", "frontend", "python"]
  pull_request:
    branches: ["main"]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  front:
    name: Frontend CI/CD
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/frontend'
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # - name: Set up node
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: "20.x"

      - name: docker Down
        run: docker compose down

      - name: docker remove image
        run: docker rmi nmm_frontend
        continue-on-error: true

      - name: docker up
        run: docker compose up -d --build

  backend:
    name: Backend CI/CD
    runs-on: Linux
    environment: JUNGLE_SECRET
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/backend'
    defaults:
      run:
        working-directory: ./express-server

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # - name: Set up node
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: "20.x"

      - name: Create .env file
        run: |
          echo "ACCESS_TOKEN_SECRET=${{ secrets.ACCESS_TOKEN_SECRET }}" >> .env 
          echo "REFRESH_TOKEN_SECRET=${{ secrets.REFRESH_TOKEN_SECRET }}" >> .env 
          echo "S3_ACCESS_KEY=${{ secrets.S3_ACCESS_KEY }}" >> .env 
          echo "S3_SECRET_ACCESS_KEY=${{ secrets.S3_SECRET_ACCESS_KEY }}" >> .env
          echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> .env 
          echo "AWS_BUCKET=${{ secrets.AWS_BUCKET }}" >> .env 
          cat .env

      - name: docker Down
        run: docker compose down

      - name: docker remove image
        run: docker rmi nmm_backend
        continue-on-error: true

      - name: docker up
        run: docker compose up -d --build

  python:
    name: Python CI/CD
    runs-on: self-hosted
    environment: JUNGLE_SECRET
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/python'
    defaults:
      run:
        working-directory: ./django-server

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # - name: Set up python
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: "3.12"

      - name: Create .env file
        run: |
          echo "ACCESS_TOKEN_SECRET=${{ secrets.ACCESS_TOKEN_SECRET }}" >> .env 
          echo "REFRESH_TOKEN_SECRET=${{ secrets.REFRESH_TOKEN_SECRET }}" >> .env 
          echo "AWS_ACCESS_KEY_ID=${{ secrets.S3_ACCESS_KEY }}" >> .env 
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.S3_SECRET_ACCESS_KEY }}" >> .env
          echo "AWS_S3_REGION_NAME=${{ secrets.AWS_REGION }}" >> .env 
          echo "AWS_STORAGE_BUCKET_NAME=${{ secrets.AWS_BUCKET }}" >> .env 
          echo "DATABASE_USER=${{ secrets.DATABASE_USER }}" >> .env 
          echo "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" >> .env 
          echo "DATABASE_ENGINE=${{vars.DATABASE_ENGINE}}" >> .env 
          echo "DATABASE_NAME=${{vars.DATABASE_NAME}}" >> .env 
          echo "DATABASE_HOST=${{vars.DATABASE_HOST}}" >> .env 
          echo "DATABASE_PORT=${{vars.DATABASE_PORT}}" >> .env 
          cat .env

      - name: docker Down
        run: docker compose down

      - name: docker remove image
        run: docker rmi nmm_django
        continue-on-error: true

      - name: docker up
        run: docker compose up -d --build
